### ISSUE TITLE
Will c4 work with the Arduino IDE?

### ISSUE THREAD

**Issue by znmeb** [CCurl/c4#19]
I've read through most of your Forth / virtual machines and I saw that some of them are configured to run as Arduino sketches and some aren't. I'm assuming that this is a capacity limitation; many Arduino devices aren't big enough to support a full Forth.

I'm working with larger microcontrollers - the ESP32-S3, -C3 and C6, the Teensy 4.1 and the RP2040 / RP2350. They all have plenty of RAM and flash and full 32-bit ALUs. How hard would it be to get c4 running as an Arduino sketch?

**Comment by CCurl** [comment]
Yes, it should. It would be essentially a question of creating a .INO file that does something similar to what `system.c` does. I think you'd also have to either rename the files as .cpp or use `extern "C" {}` to identify the C functions, because I think the Arduino stuff is all C++.

Then you'd probably want to build LittleFS wrappers (or something similar) for the file functions in `file.c` (or just stubs that do nothing if you don't want/need to support files).

I have done this kind of thing for other projects (eg - see the c3 repo, `fs-teensy.cpp`). I decided not to do it for c4 because I want to keep it as simple/uncomplicated as possible.

So it's essentially ... create Arduino-specific files to replace `system.c` and `file.c`

**Comment by znmeb** [comment]
Thanks! I've looked at a few of your other projects that are already configured for Arduino ... I may just start with one of those and bring them up to where I need them. Token threading is fine for what I'm doing, but I do need Forth syntax rather than a human-readable assembly language. BoardForth seems to be close enough for the moment.

**Comment by CCurl** [comment]
FWIW, BoardForth was a pretty early effort ...

I was much happier with c3, but I am not sure how much I tested that one on Arduino boards. I think I used a RPI Pico mostly when I was doing that.

**Comment by znmeb** [comment]
> FWIW, BoardForth was a pretty early effort ...
> 
> I was much happier with c3, but I am not sure how much I tested that one on Arduino boards. I think I used a RPI Pico mostly when I was doing that.

My targets are RP2350 / RP2040, Teensy 4.1 and ESP32-S3/C3/C6, Nice to have is an Electro-Smith Daisy, which has an Arduino "core" but needs STM32Cube to upload firmware. I probably need LittleFS, although I can probably live with a host process uploading a bunch of Forth code after each power cycle.
